import fs from "fs";
const file = "src/store/chatStore.ts";
let content = fs.readFileSync(file, "utf8");

content = content.replace(
  "  deleteConversation: (conversationId: string) => void;\n      updateToolCall: (conversationId, messageId, updates) => set((state) => ({\n        conversations: state.conversations.map(c => \n          c.id === conversationId \n            ? {\n                ...c,\n                messages: c.messages.map(m => \n                  m.id === messageId \n                    ? { ...m, toolCall: m.toolCall ? { ...m.toolCall, ...updates } : undefined }\n                    : m\n                ),\n                updatedAt: Date.now()\n              }\n            : c\n        )\n      })),\n      deleteConversation: (conversationId) => set((state) => ({",
  "  deleteConversation: (conversationId: string) => void;\n}\n\nexport const useChatStore = create<ChatState>()(\n  persist(\n    (set) => ({\n      conversations: [],\n      activeConversationId: null,\n      createConversation: (title = 'New Conversation') => {\n        const id = Date.now().toString();\n        const newConv: Conversation = { id, title, messages: [], updatedAt: Date.now() };\n        set((state) => ({\n          conversations: [newConv, ...state.conversations],\n          activeConversationId: id,\n        }));\n        return id;\n      },\n      setActiveConversation: (id) => set({ activeConversationId: id }),\n      addMessage: (conversationId, message) => set((state) => ({\n        conversations: state.conversations.map(c => \n          c.id === conversationId \n            ? { ...c, messages: [...c.messages, message], updatedAt: Date.now() }\n            : c\n        )\n      })),\n      updateMessageStream: (conversationId, messageId, chunk) => set((state) => ({\n        conversations: state.conversations.map(c => \n          c.id === conversationId \n            ? {\n                ...c,\n                messages: c.messages.map(m => \n                  m.id === messageId \n                    ? { ...m, content: m.content + chunk }\n                    : m\n                ),\n                updatedAt: Date.now()\n              }\n            : c\n        )\n      })),\n      updateToolCall: (conversationId, messageId, updates) => set((state) => ({\n        conversations: state.conversations.map(c => \n          c.id === conversationId \n            ? {\n                ...c,\n                messages: c.messages.map(m => \n                  m.id === messageId \n                    ? { ...m, toolCall: m.toolCall ? { ...m.toolCall, ...updates } : { ...updates } as any }\n                    : m\n                ),\n                updatedAt: Date.now()\n              }\n            : c\n        )\n      })),\n      editUserMessageAndTruncate: (conversationId, messageId, newContent) => set((state) => ({\n        conversations: state.conversations.map(c => {\n          if (c.id !== conversationId) return c;\n          const idx = c.messages.findIndex(m => m.id === messageId);\n          if (idx === -1) return c;\n          const updated = [...c.messages.slice(0, idx + 1)];\n          updated[idx] = { ...updated[idx], content: newContent, timestamp: Date.now() };\n          return { ...c, messages: updated, updatedAt: Date.now() };\n        })\n      })),\n      truncateAfterMessage: (conversationId, messageId) => set((state) => ({\n        conversations: state.conversations.map(c => {\n          if (c.id !== conversationId) return c;\n          const idx = c.messages.findIndex(m => m.id === messageId);\n          if (idx === -1) return c;\n          return { ...c, messages: c.messages.slice(0, idx), updatedAt: Date.now() };\n        })\n      })),\n      deleteConversation: (conversationId) => set((state) => ({"
);

fs.writeFileSync(file, content);
